sonar.projectKey=devops-project
sonar.projectName=DevOps Pipeline

sonar.sources=app
sonar.language=py

sonar.python.version=3

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8

sonar.exclusions=venv/**,__pycache__/**,*.pyc